// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEzXUKU3OBCndw3QXqsuqcQ6MYbXGvosw',
    appId: '1:827439833710:android:823381cb816ca011d3fc7f',
    messagingSenderId: '827439833710',
    projectId: 'fixpair-606c8',
    storageBucket: 'fixpair-606c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCWg5VXj04EsRrepmASSkYK5JsUUzmS6E',
    appId: '1:827439833710:ios:a106dcd6e2cc28a3d3fc7f',
    messagingSenderId: '827439833710',
    projectId: 'fixpair-606c8',
    storageBucket: 'fixpair-606c8.firebasestorage.app',
    iosBundleId: 'com.fixpair.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGyiEUvWbGjoGo8C6Vp_2afFUs8lQDfIw',
    appId: '1:827439833710:web:f6abe3f03c0be275d3fc7f',
    messagingSenderId: '827439833710',
    projectId: 'fixpair-606c8',
    authDomain: 'fixpair-606c8.firebaseapp.com',
    storageBucket: 'fixpair-606c8.firebasestorage.app',
    measurementId: 'G-MDMLWLTXKN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCWg5VXj04EsRrepmASSkYK5JsUUzmS6E',
    appId: '1:827439833710:ios:413a87c1efe1117ad3fc7f',
    messagingSenderId: '827439833710',
    projectId: 'fixpair-606c8',
    storageBucket: 'fixpair-606c8.firebasestorage.app',
    iosBundleId: 'com.example.fixpair',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGyiEUvWbGjoGo8C6Vp_2afFUs8lQDfIw',
    appId: '1:827439833710:web:3752de068763a372d3fc7f',
    messagingSenderId: '827439833710',
    projectId: 'fixpair-606c8',
    authDomain: 'fixpair-606c8.firebaseapp.com',
    storageBucket: 'fixpair-606c8.firebasestorage.app',
    measurementId: 'G-EBS9P6D76E',
  );

}